import type { Metadata } from 'next'
import './globals.css'
import { fontVariables } from '@/shared/config'

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang='ru' className={fontVariables}>
      <body>{children}</body>
    </html>
  )
}
